# Generated by Django 5.1.3 on 2025-01-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_rev', models.AutoField(primary_key=True, serialize=False)),
                ('fechain_rev', models.DateField()),
                ('fechfin_rev', models.DateField()),
                ('tipaloj_rev', models.CharField(choices=[('Tienda', 'Recreativo'), ('Cabaña', 'Cabaña'), ('Caravana', 'Caravana')], default='Tienda', max_length=20)),
                ('numpers_rev', models.CharField(max_length=200)),
                ('estado_rev', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente')], default='Confirmada', max_length=20)),
                ('obser_rev', models.CharField(max_length=500)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campistas', to='Gestiones.campistas')),
            ],
        ),
    ]
