# Generated by Django 5.1.3 on 2025-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiones', '0002_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='obser_rev',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='tipaloj_rev',
            field=models.CharField(choices=[('Tienda', 'Tienda'), ('Cabaña', 'Cabaña'), ('Caravana', 'Caravana')], default='Tienda', max_length=20),
        ),
    ]
